.class final Lrx/Completable$6;
.super Ljava/lang/Object;
.source "Completable.java"

# interfaces
.implements Lrx/Completable$OnSubscribe;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lrx/Completable;->error(Lrx/functions/Func0;)Lrx/Completable;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x8
    name = null
.end annotation


# instance fields
.field final synthetic val$errorFunc0:Lrx/functions/Func0;


# direct methods
.method constructor <init>(Lrx/functions/Func0;)V
    .locals 0

    .line 417
    iput-object p1, p0, Lrx/Completable$6;->val$errorFunc0:Lrx/functions/Func0;

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods
.method public bridge synthetic call(Ljava/lang/Object;)V
    .locals 1
    .param p1, "x0"    # Ljava/lang/Object;

    .line 417
    move-object v0, p1

    check-cast v0, Lrx/CompletableSubscriber;

    invoke-virtual {p0, v0}, Lrx/Completable$6;->call(Lrx/CompletableSubscriber;)V

    return-void
.end method

.method public call(Lrx/CompletableSubscriber;)V
    .locals 3
    .param p1, "s"    # Lrx/CompletableSubscriber;

    .line 420
    invoke-static {}, Lrx/subscriptions/Subscriptions;->unsubscribed()Lrx/Subscription;

    move-result-object v0

    invoke-interface {p1, v0}, Lrx/CompletableSubscriber;->onSubscribe(Lrx/Subscription;)V

    .line 424
    const/4 v0, 0x0

    :try_start_0
    iget-object v1, p0, Lrx/Completable$6;->val$errorFunc0:Lrx/functions/Func0;

    invoke-interface {v1}, Lrx/functions/Func0;->call()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Ljava/lang/Throwable;
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    move-object v0, v1

    .line 427
    .local v0, "error":Ljava/lang/Throwable;
    goto :goto_0

    .line 425
    .end local v0    # "error":Ljava/lang/Throwable;
    :catchall_0
    move-exception v1

    .line 426
    .restart local v0    # "error":Ljava/lang/Throwable;
    .local v1, "e":Ljava/lang/Throwable;
    move-object v0, v1

    .line 429
    .end local v1    # "e":Ljava/lang/Throwable;
    :goto_0
    if-nez v0, :cond_0

    .line 430
    new-instance v1, Ljava/lang/NullPointerException;

    const-string v2, "The error supplied is null"

    invoke-direct {v1, v2}, Ljava/lang/NullPointerException;-><init>(Ljava/lang/String;)V

    move-object v0, v1

    .line 432
    :cond_0
    invoke-interface {p1, v0}, Lrx/CompletableSubscriber;->onError(Ljava/lang/Throwable;)V

    .line 433
    return-void
.end method
